---
apiVersion: v1
kind: Pod
metadata:
  labels:
    id: holy-api
  name: holy-api
  namespace: pluto
spec:
  containers:
    - env:
        - name: CACHE_KEY_1
          value: b&MTCi0=[T66RXm!jO@
        - name: CACHE_KEY_2
          value: PCAILGej5Ld@Q%{Q1=#
        - name: CACHE_KEY_3
          value: 2qz-]2OJlWDSTn_;RFQ
      image: bitnami/nginx
      name: holy-api-container
      volumeMounts:
        - mountPath: /cache1
          name: cache-volume1
        - mountPath: /cache2
          name: cache-volume2
        - mountPath: /cache3
          name: cache-volume3
  volumes:
    - emptyDir: {}
      name: cache-volume1
    - emptyDir: {}
      name: cache-volume2
    - emptyDir: {}
      name: cache-volume3
